name: Auto Minor Version Bump and Release

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js (for semantic versioning tool)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Bump minor version and push tag
        run: |
          git fetch --prune --unshallow || true
          CURRENT_VERSION=$(git describe --tags --abbrev=0)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

      - name: Create GitHub Release with gh
        run: |
          gh release create $NEW_VERSION --title "$NEW_VERSION" --notes "Release notes here"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
