name: Auto Minor Version Bump and Release

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump minor version and push tag
        id: version_step
        run: |
          CURRENT_VERSION=$(git describe --tags --abbrev=0)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "::set-output name=new_version::$NEW_VERSION"
          git tag $NEW_VERSION
          git push origin $NEW_VERSION

      - name: Create GitHub Release
        run: |
          gh release create ${{ steps.version_step.outputs.new_version }} --generate-notes
